apiVersion: apps/v1
kind: Deployment
metadata:
  name: realfinal-app
  namespace: default
  labels:
    app: realfinal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: realfinal
  template:
    metadata:
      labels:
        app: realfinal
    spec:
      containers:
      - name: realfinal
        image: 20107946/realfinal:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 7000
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017/realfinal" # Placeholder: Update with actual URI

---
apiVersion: v1
kind: Service
metadata:
  name: realfinal-service
  namespace: default
spec:
  selector:
    app: realfinal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7000
  type: ClusterIP
